MAPR-YARN-23: Set the auth methods.
java.lang.AssertionError: Couldn't create MiniKDC
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.apache.hadoop.yarn.server.resourcemanager.webapp.TestRMWebServicesDelegationTokenAuthentication.setUp(TestRMWebServicesDelegationTokenAuthentication.java:104)

(cherry picked from commit 0677582)