MAPR-YARN-11: Fix tests after MAPR-26042: Incorrect group ownership for container logs.
We should use real user name to create ContainerTokenIdentifier.
java.lang.AssertionError: There should be files or Dirs under nm_private when container is launched

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.yarn.server.nodemanager.TestNodeManagerReboot.testClearLocalDirWhenNodeReboot(TestNodeManagerReboot.java:188)

(cherry picked from commit dfe5bd5f58003ff91ad64b3d59e53df19c593900)