MAPR-YARN-19: Assert is not correct for MapR  because of commit: "Enable yarn webapps to listen to all nics by default." (916664586c65369d2a3b883b5088b13abd49b595)
 java.lang.AssertionError: Web app address still unbound to a host at 0.0.0.0:45614