MAPR-YARN-11: hadoop-yarn-server-resourcemanager repairing
Added required configuration parameters. The exception was caused because in org.apache.hadoop.ipc.Server#getAuthMethods() should be only one auth method (TOKEN), but actually, we have two(TOKEN, SIMPLE). Here (SIMPLE) authentication method was got as a default parameter, but in this place, we need to set authentication method (TOKEN) in config.

Exception:
org.apache.hadoop.yarn.exceptions.YarnException: No AMRMToken found for user appattempt_1521201270392_0001_000001

(cherry picked from commit dfce77c)