MAPR-YARN-8. hadoop-yarn-server-applicationhistoryservice repairing Make "getMaprDelegationTokenAuthenticator" public for mock in tests from different packages. Set auth methods. Set "hadoop.login" to "kerberos" after changing in security (Security: Support configuration based JAAS login and negotiable RPC authentication. 65abcda1d866cb15159fdaad7399d97000aed1c9). If we do not specify "hadoop.login" property then will be used "hadoop_default" (See UserGroupInformation#initialize()). It's not acceptable for tests that use kerberos authentication. Also, we do relogin from keytab ("UserGroupInformation.getLoginUser().reloginFromKeytab();") because to do authentication via "hadoop_kerberos" we should use "ticket cache" (See "test.login.conf" and "mapr.login.conf" files). Ticket cache stored in "/tmp/krb5cc_5000" on a cluster but not exist during JUnit tests.
Errors:
1. Without "hadoop.login"="kerberos":
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator$1.run(KerberosAuthenticator.java:285)
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator$1.run(KerberosAuthenticator.java:261)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.doSpnegoSequence(KerberosAuthenticator.java:261)

2. Without relogin from keytab:
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.io.IOException: failure to login: javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication
Caused by: javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication
	at com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:841)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:704)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:724)

(cherry picked from commit 6690c60)