MAPR-YARN-49: Changed value of DEFAULT_NM_RECOVERY_ENABLED property since after MAPR-26008 YarnConfiguration.DEFAULT_NM_RECOVERY_ENABLED field has been changed to "true"
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.io.IOException: NodeManager 0 failed to start

	at org.apache.hadoop.yarn.server.MiniYARNCluster$NodeManagerWrapper.serviceStart(MiniYARNCluster.java:579)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)

(cherry picked from commit 3c50e3388ec22d9cd1e40995e56492ba72d0616f)