MAPR-YARN-11: Changed the expected value because the disks were added as a resource. Added four the disks properties:     reservedDisks     availableDisks     allocatedDisks     totalDisks (Bug 20762 - Cluster Metrics does not show disk as a resource)
java.lang.AssertionError: incorrect number of elements
Expected :23
Actual   :27

at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.hadoop.yarn.server.resourcemanager.webapp.TestRMWebServices.verifyClusterMetricsJSON(TestRMWebServices.java:423)
	at org.apache.hadoop.yarn.server.resourcemanager.webapp.TestRMWebServices.testClusterMetrics(TestRMWebServices.java:345)

(cherry picked from commit 5b7241a)