MAPR-YARN-13: hadoop-yarn-server-tests repairing
Change error message in case if we don't send any NMToken, because of commit "Security: Support configuration based JAAS login and negotiable RPC authentication. 65abcda1d866cb15159fdaad7399d97000aed1c9" that has a lot of changes in security realization.

If security disabled:
java.lang.NullPointerException
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.authorizeUser(ContainerManagerImpl.java:650)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.startContainers(ContainerManagerImpl.java:718)
	at org.apache.hadoop.yarn.api.impl.pb.service.ContainerManagementProtocolPBServiceImpl.startContainers(ContainerManagementProtocolPBServiceImpl.java:60)
	at org.apache.hadoop.yarn.proto.ContainerManagementProtocol$ContainerManagementProtocolService$2.callBlockingMethod(ContainerManagementProtocol.java:95) ...

If security enabled:
java.io.IOException: Failed on local exception: java.io.IOException: Server asks us to fall back to SIMPLE auth, but this client is configured to only allow secure connections.; Host Details : local host is: "PC/127.0.1.1"; destination host is: "192.168.0.139":35551;
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1482)
	at org.apache.hadoop.ipc.Client.call(Client.java:1409)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229) ...

(cherry picked from commit 1681aa479602ba286460ec932cb76c5a743b3905)