MAPR-YARN-7: repairing security in hadoop-yarn-registry JUnit tests * Set the auth methods java.lang.NullPointerException 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2229) 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2194) 	at org.apache.hadoop.security.SecurityUtil.getCustomAuthPrincipal(SecurityUtil.java:634) 	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:219) 	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:361)
* Set "hadoop.login" to "kerberos"
java.lang.NullPointerException: null
	at org.apache.hadoop.registry.client.impl.zk.RegistrySecurity.aclToString(RegistrySecurity.java:822)
	at org.apache.hadoop.registry.client.impl.zk.RegistrySecurity.aclsToString(RegistrySecurity.java:807)
	at org.apache.hadoop.registry.server.services.RegistryAdminService.serviceInit(RegistryAdminService.java:201)
	at org.apache.hadoop.registry.server.integration.RMRegistryOperationsService.serviceInit(RMRegistryOperationsService.java:77)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.registry.secure.TestSecureRMRegistryOperations$1.run(TestSecureRMRegistryOperations.java:103)
	at org.apache.hadoop.registry.secure.TestSecureRMRegistryOperations$1.run(TestSecureRMRegistryOperations.java:97)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1633)

* Refresh JAAS configuration so we can run all test from the hadoop-yarn-registry module simultaneously
java.lang.RuntimeException: Entry "ZOOKEEPER_SERVER" not found; JAAS config = ; java.security.auth.login.config=/../private-hadoop-common/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-registry/target/kdc/jaas.txt

	at org.apache.hadoop.registry.client.impl.zk.RegistrySecurity.validateContext(RegistrySecurity.java:693)
	at org.apache.hadoop.registry.secure.AbstractSecureRegistryTest.createSecureZKInstance(AbstractSecureRegistryTest.java:300)
	at org.apache.hadoop.registry.secure.AbstractSecureRegistryTest.startSecureZK(AbstractSecureRegistryTest.java:380)
java.lang.RuntimeException: Entry "alice" not found; JAAS config = ; java.security.auth.login.config=/../private-hadoop-common/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-registry/target/kdc/jaas.txt

	at org.apache.hadoop.registry.client.impl.zk.RegistrySecurity.validateContext(RegistrySecurity.java:693)
	at org.apache.hadoop.registry.client.impl.zk.RegistrySecurity.setZKSaslClientProperties(RegistrySecurity.java:738)

(cherry picked from commit e893ccd2673f52984b6a5ecccf31603f1468d907)