MAPR-YARN-49: Changed expected exception since MAPR-14574.
java.io.IOException: Output directory .../private-hadoop-common/hadoop-mapreduce-project/hadoop-mapreduce-examples/target/test-dir/terasort/sortout already exists.

	at org.apache.hadoop.examples.terasort.TeraSort.run(TeraSort.java:286)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.examples.terasort.TestTeraSort.runTeraSort(TestTeraSort.java:67)
	at org.apache.hadoop.examples.terasort.TestTeraSort.testTeraSort(TestTeraSort.java:96)

(cherry picked from commit 93aa9f591372369cf091284676287790f711fc05)