MAPR-YARN-49: fix for TestEvents.testEvents - set servicesMetaData to datum
java.lang.NullPointerException: null of map in field servicesMetaData of org.apache.hadoop.mapreduce.jobhistory.TaskAttemptStarted of union in field event of org.apache.hadoop.mapreduce.jobhistory.Event

	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:93)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:87)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at org.apache.hadoop.mapreduce.jobhistory.EventWriter.write(EventWriter.java:83)
	at org.apache.hadoop.mapreduce.jobhistory.TestEvents.getEvents(TestEvents.java:200)
	at org.apache.hadoop.mapreduce.jobhistory.TestEvents.testEvents(TestEvents.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
Caused by: java.lang.NullPointerException