MAPR-YARN-49: Only one cluster can be existing at any point of time (See MiniDFSCluster#build())
java.net.ConnectException: Call From "hostname"/127.0.1.1 to localhost:44737 failed on connection exception:
java.net.ConnectException: Connection refused;

(cherry picked from commit 829d2d2bef4f610bfa6928a15aa415acbdc0ca56)