MAPR-YARN-49: Mocked MapOutputFile.setConf() method since Bug 13594 added setting "mapr.host" property
java.lang.IllegalArgumentException: The value of property mapr.host must not be null

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1147)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1128)
	at org.apache.hadoop.mapred.MapRFsOutputFile.getMapRFsPath(MapRFsOutputFile.java:342)
	at org.apache.hadoop.mapred.MapRFsOutputFile.getMapRLocalOutputDir(MapRFsOutputFile.java:347)
	at org.apache.hadoop.mapred.MapRFsOutputFile.setLocalDirs(MapRFsOutputFile.java:114)
	at org.apache.hadoop.mapred.MapRFsOutputFile.setConf(MapRFsOutputFile.java:102)
	at org.apache.hadoop.mapreduce.task.reduce.DirectShuffleMergeManagerImpl.<init>(DirectShuffleMergeManagerImpl.java:161)
	at org.apache.hadoop.mapreduce.task.reduce.TestDirectShuffleMergeManager.testOnDiskMerger(TestDirectShuffleMergeManager.java:272)

(cherry picked from commit 898a870d7ccfc29853e3444dab98e515c5ee47e2)