MAPR-15031: Catch OOM when mapper runs out of memory reading a large input line record. When a mapper tries to read a large input line record, it can potentially run out of memory. Currently, the user does not know why the mapper ran out of memory. This change tries to log the OOME and suggest a potential value for capping the line length.
Testing

Ran a wordcount with input line record ~260MB. Before the fix, the job fails with "Error: Java heap space". After the fix, the job fails with the following error:

Error: java.io.IOException: Out of memory error while reading a very large single line input record. To skip this record set mapreduce.input.linerecordreader.line.maxlength to a lower value. Current value: 2147483647, jvm heap size: 838860800, potential value: 26214400

The full stack trace is logged as well.

The job succeeds when tried with -Dmapreduce.input.linerecordreader.line.maxlength=26214400