MAPR-YARN-49: Added property "servicesMetaData" to jhist files since this property was added by fix of Bug 13261 (Get MRAppMaster HA work with direct shuffle)
org.apache.avro.AvroTypeException: Found org.apache.hadoop.mapreduce.jobhistory.TaskAttemptStarted, expecting org.apache.hadoop.mapreduce.jobhistory.TaskAttemptStarted, missing required field servicesMetaData

(cherry picked from commit 4fed2cef5fe39616b020e25f2ac24ec480ddc607)