MAPR-YARN-11: Changed values for vCores and disks for TestCapacityScheduler#testApplicationHeadRoom
java.lang.AssertionError: expected:<<memory:4096, vCores:1, disks:1.0>> but was:<<memory:4096, vCores:100, disks:100.0>>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.TestCapacityScheduler.testApplicationHeadRoom(TestCapacityScheduler.java:2698)

(cherry picked from commit 521161cbb0fec5c790e1c5a1f03e08265024f1fe)