bugfix 13130 AsyncHBase atomic increment request failed against yarn cluster
QA teams hbase.testBufferedAtomicIncrement test was failing as the test was built against Google Guava version 13.0.1
but was being executed against version 11.0.2. This was causing the test to fail with exception java.lang.NoSuchMethodError
as the recordStats() method was missing from the com.google.common.cache.CacheBuilder class. This method is present in the
new Guava jar and not the old one. So upgrading the dependency to 13.0.1.

As part of this bug fix I am also updating the version of Google guava in the libs folder to 13.0.1.
I am thinking of not sending a separate review request for that as there is not code change, only a change in the binary.

Reviewed by: Kannan Rajah, Smidth Panchamia, Santosh Marella
http://rboard.corp.maprtech.com/r/129/