MAPR-15296: Figure out authentication method from JAAS config rather than from "hadoop.security.authentication".
- Obtain UGI's authenticationMethod from JAAS config
- Return the same via SecurityUtil.getAuthenticationMethod().

Installed mapr-oozie_4.0.0.26126_all.deb from http://archive2.mapr.com/releases/ecosystem-all/ubuntu/.

Before the fix, oozie wouldn't start with the following exception:
2014-11-11 08:46:20,945 FATAL Services:533 - USER[-] GROUP[-] E0100: Could not initialize service [org.apache.oozie.service.HadoopAccessorService], Can't get Kerberos realm
org.apache.oozie.service.ServiceException: E0100: Could not initialize service [org.apache.oozie.service.HadoopAccessorService], Can't get Kerberos realm
        at org.apache.oozie.service.HadoopAccessorService.kerberosInit(HadoopAccessorService.java:197)
        at org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:142)
        at org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:113)
        at org.apache.oozie.service.Services.setServiceInternal(Services.java:368)
        at org.apache.oozie.service.Services.setService(Services.java:354)
        at org.apache.oozie.service.Services.loadServices(Services.java:287)
        at org.apache.oozie.service.Services.init(Services.java:208)
        at org.apache.oozie.servlet.ServicesLoader.contextInitialized(ServicesLoader.java:39)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4206)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4705)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:943)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:778)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:504)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: java.lang.IllegalArgumentException: Can't get Kerberos realm
        at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
        at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:272)
        at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:308)
        at org.apache.oozie.service.HadoopAccessorService.kerberosInit(HadoopAccessorService.java:188)
        ... 31 more

After the fix, this exception is not seen. oozie logs print the following:
2014-11-11 10:00:31,253 DEBUG UserGroupInformation:199 - HADOOP_SECURITY_AUTHENTICATION is set to: KERBEROS
2014-11-11 10:00:31,253 DEBUG UserGroupInformation:199 - HADOOP_SECURITY_AUTHENTICATION is set to: KERBEROS
2014-11-11 10:00:31,299 DEBUG UserGroupInformation:215 - Security is enabled.
2014-11-11 10:00:31,299 DEBUG UserGroupInformation:215 - Security is enabled.
2014-11-11 10:00:31,300 DEBUG UserGroupInformation:230 - Login configuration entry is hadoop_maprsasl
2014-11-11 10:00:31,300 DEBUG UserGroupInformation:230 - Login configuration entry is hadoop_maprsasl
2014-11-11 10:00:31,300  INFO UserGroupInformation:324 - authenticationMethod from JAAS configuration:CUSTOM
2014-11-11 10:00:31,300  INFO UserGroupInformation:324 - authenticationMethod from JAAS configuration:CUSTOM