MAPR-YARN-49: Changed default value MR_HISTORY_WEBAPP_IS_ALL_IFACES in test to check needed functionality since commit 916664586c65369d2a3b883b5088b13abd49b595
java.lang.IllegalArgumentException: port out of range:424242

After reduced port:
java.lang.AssertionError:
Expected :http://example.net:42442/jobhistory/job/job_6384623_0005
Actual   :http://0.0.0.0:42442/jobhistory/job/job_6384623_0005

(cherry picked from commit 58feacd0eb6c11885bdf20229957f7d3574f59b2)