MAPR-YARN-49: Added static resolution for test hosts since MAPR-24639
java.net.UnknownHostException: hostname
	at org.apache.hadoop.yarn.server.resourcemanager.scheduler.fifo.FifoScheduler.nodeUpdate(FifoScheduler.java:800)
	at org.apache.hadoop.yarn.server.resourcemanager.scheduler.fifo.FifoScheduler.handle(FifoScheduler.java:862)
	at org.apache.hadoop.yarn.server.resourcemanager.scheduler.fifo.FifoScheduler.handle(FifoScheduler.java:105)
	at org.apache.hadoop.mapreduce.v2.app.rm.TestRMContainerAllocator$MyResourceManager$1.handle(TestRMContainerAllocator.java:672)
	at org.apache.hadoop.mapreduce.v2.app.rm.TestRMContainerAllocator$MyResourceManager$1.handle(TestRMContainerAllocator.java:669)
	at org.apache.hadoop.yarn.event.AsyncDispatcher.dispatch(AsyncDispatcher.java:175)
	at org.apache.hadoop.yarn.event.AsyncDispatcher$1.run(AsyncDispatcher.java:108)

	as a result:
	java.lang.AssertionError: AppAttempt state is not correct (timedout)
    Expected :ALLOCATED
    Actual   :SCHEDULED

(cherry picked from commit dadc268dda824dffa55971c02ff7b6a9f82bd663)