Accommodating for changes in signature to constructor of IFile.Writer class
Accommodating for changes in signature to constructor of IFile$Writer class
Not sure how this compiled in the first place but I was seeing following errors when running reducer.

Looked at Open Source ShuffleMergeManagerImpl.java on how then had handled the interface change and did similar changes.

15/02/20 15:15:24 INFO mapreduce.Job: Task Id : attempt_1424473621144_0004_r_000000_2, Status : FAILED
Error: org.apache.hadoop.mapreduce.task.reduce.Shuffle$ShuffleError: Error while doing final merge
        at org.apache.hadoop.mapreduce.task.reduce.DirectShuffle.run(DirectShuffle.java:154)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:376)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1566)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.mapred.IFile$Writer.<init>(Lorg/apache/hadoop/conf/Configuration;Lorg/apache/hadoop/fs/FileSystem;Lorg/apache/hadoop/fs/Path;Ljava/lang/Class;Ljava/lang/Class;Lorg/apache/hadoop/io/compress/CompressionCodec;Lorg/apache/hadoop/mapred/Counters$Counter;)V
        at org.apache.hadoop.mapreduce.task.reduce.DirectShuffleMergeManagerImpl.finalMerge(DirectShuffleMergeManagerImpl.java:734)
        at org.apache.hadoop.mapreduce.task.reduce.DirectShuffleMergeManagerImpl.close(DirectShuffleMergeManagerImpl.java:379)
        at org.apache.hadoop.mapreduce.task.reduce.DirectShuffle.run(DirectShuffle.java:152)
        ... 6 more