Revert "MAPR-30945. yarn node -list command is failing with "java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.LogManager""
This reverts commit 1d392d0