MAPR-YARN-49: Added few constructors that set disks since disks was added as a resource
java.lang.AssertionError: Task state is not correct (timedout)
Expected :RUNNING
Actual   :SCHEDULED

(cherry picked from commit 427d8a7b4aaff5f6bfb59630333961d58492cd75)
(cherry picked from commit 0c06570e4f3986ea309a8047b748ac4766f1d03a)